# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('author', models.CharField(max_length=4)),
                ('media', models.TextField()),
                ('country', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=25)),
                ('product', models.CharField(max_length=25)),
                ('term', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
                ('analysis', models.CharField(max_length=4)),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xml_parse.Headers')),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('keywords', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=30)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='story',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xml_parse.Stories'),
        ),
        migrations.AddField(
            model_name='headers',
            name='mediatype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xml_parse.MediaType'),
        ),
    ]
